### ISSUE TITLE
MHD

### ISSUE THREAD

**Issue by MarekVigas** [Adman/python-cpsk-api#2]
cp.sk ponúka aj informácie o MHD. Je nejaký spôsob ako cez API získavať aj tieto dáta ?

**Comment by Adman** [comment]
@vigas147 Dakujem za issue.
Ono to tam bolo implementovane, iba `fc` a `tc` parametre to pre nejaku pricinu blokovali.
`get_routes("Zochova", "Kapucinska", vehicle="vlakbusmhd")` by malo vyhladat MHD spojenie
